config/routes.rb
Rails.application.routes.draw do

  resources :medicines
  resources :procedures
  resources :patients
  get 'pages/info'
 
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", registrations: "users/registrations" }
  
  root to: "pages#info"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/medicine.rb
class Medicine < ApplicationRecord
	belongs_to :patient
end

app/controllers/medicines_controller.rb
class MedicinesController < ApplicationController
  before_action :set_medicine, only: [:show, :edit, :update, :destroy]

  # GET /medicines
  # GET /medicines.json
  def index
    @medicines = Medicine.all
    
  end

  # GET /medicines/1
  # GET /medicines/1.json
  def show
    @medicine = Medicine.find(params[:id])
    @patient = @medicine.patient_id
  end

  # GET /medicines/new
  def new
    @medicine = Medicine.new
  end

  # GET /medicines/1/edit
  def edit
  end

  # POST /medicines
  # POST /medicines.json
  def create
    @medicine = Medicine.new(medicine_params)
    respond_to do |format|
      if @medicine.save
        format.html { redirect_to @medicine, notice: 'Medicine was successfully created.' }
        format.json { render :show, status: :created, location: @medicine }
      else
        format.html { render :new }
        format.json { render json: @medicine.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /medicines/1
  # PATCH/PUT /medicines/1.json
  def update
    respond_to do |format|
      if @medicine.update(medicine_params)
        format.html { redirect_to @medicine, notice: 'Medicine was successfully updated.' }
        format.json { render :show, status: :ok, location: @medicine }
      else
        format.html { render :edit }
        format.json { render json: @medicine.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /medicines/1
  # DELETE /medicines/1.json
  def destroy
    @medicine.destroy
    respond_to do |format|
      format.html { redirect_to medicines_url, notice: 'Medicine was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_medicine
      @medicine = Medicine.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def medicine_params
      params.require(:medicine).permit(:med_name, :dosage, :in_take, :date, :patient_id)
    end
end

app/helpers/medicines_helper.rb
module MedicinesHelper
end

app/views/medicines/_form.html.erb
<%= form_with(model: medicine, local: true) do |form| %>
  <% if medicine.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(medicine.errors.count, "error") %> prohibited this medicine from being saved:</h2>

      <ul>
      <% medicine.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :medicine %>
    <%= form.text_field :med_name, id: :medicine_med_name %>
  </div>

  <div class="field">
    <%= form.label :dosage %>
    <%= form.text_field :dosage, id: :medicine_dosage %>
  </div>

  <div class="field">
    <%= form.label :in_take %>
    <%= form.text_field :in_take, id: :medicine_in_take %>
  </div>

  <div class="field">
    <%= form.label :prescription_date %>
    <%= form.date_select :date, id: :medicine_date %>
  </div>

   <%= form.hidden_field :patient_id %>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/medicines/edit.html.erb
<h1>Editing Medicine</h1>

<%= render 'form', medicine: @medicine %>

<%= link_to 'Show', @medicine %> |
<%= link_to 'Back', medicines_path %>

app/views/medicines/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Medicines</h1>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Med name</th>
      <th>Dosage</th>
      <th>In take</th>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @medicines.each do |medicine| %>
      <tr>
        <td><%= medicine.id %></td>
        <td><%= medicine.med_name %></td>
        <td><%= medicine.dosage %></td>
        <td><%= medicine.in_take %></td>
        <td><%= medicine.date %></td>
        <td><%= link_to 'Show', medicine %></td>
        <td><%= link_to 'Edit', edit_medicine_path(medicine) %></td>
        <td><%= link_to 'Destroy', medicine, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Medicine', new_medicine_path %>

app/views/medicines/new.html.erb
<h1>New Medicine</h1>

<%= render 'form', medicine: @medicine %>

<%= link_to 'Back', patient_path(@patient) %>

app/views/medicines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Med name:</strong>
  <%= @medicine.med_name %>
</p>

<p>
  <strong>Dosage:</strong>
  <%= @medicine.dosage %>
</p>

<p>
  <strong>In take:</strong>
  <%= @medicine.in_take %>
</p>

<p>
  <strong>Date:</strong>
  <%= @medicine.date %>
</p>

<%= link_to 'Edit', edit_medicine_path(@medicine) %> |
<%= link_to 'Back', patient_path(@patient) %>