config/routes.rb
Rails.application.routes.draw do

  resources :medicines
  resources :procedures
  resources :patients
  get 'pages/info'
 
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", registrations: "users/registrations" }
  
  root to: "pages#info"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/patient.rb
class Patient < ApplicationRecord
	mount_uploader :photo, PictureUploader
	belongs_to :user
	has_many :medicines
	has_many :procedures
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: [:show, :edit, :update, :destroy]

  # GET /patients
  # GET /patients.json
  def index
    @patients = Patient.all

  end

  # GET /patients/1
  # GET /patients/1.json
  def show

    @medicines = @patient.medicines.all
    @medicine = @patient.medicines.build

    @procedures = @patient.procedures.all
    @procedure = @patient.procedures.build    

  end

  # GET /patients/new
  def new
    @patient = Patient.new

  end

  # GET /patients/1/edit
  def edit

  end

  # POST /patients
  # POST /patients.json
  def create

    @patient = Patient.new(patient_params)
    @patient.user_id = current_user.id
    respond_to do |format|
      if @patient.save
        format.html { redirect_to @patient, notice: 'Patient was successfully created.' }
        format.json { render :show, status: :created, location: @patient }
      else
        format.html { render :new }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patients/1
  # PATCH/PUT /patients/1.json
  def update
    respond_to do |format|
      if @patient.update(patient_params)
        format.html { redirect_to @patient, notice: 'Patient was successfully updated.' }
        format.json { render :show, status: :ok, location: @patient }
      else
        format.html { render :edit }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patients/1
  # DELETE /patients/1.json
  def destroy
    @patient.destroy
    respond_to do |format|
      format.html { redirect_to patients_url, notice: 'Patient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_patient
      @patient = Patient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def patient_params
      params.require(:patient).permit(:full_name, :date_of_birth, :gender, :id_type, :id_no, :address, :phone_no, :history, :treatment, :procedure, :medicine, :photo)
    end
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/patients/_form.html.erb
<%= form_with(model: patient, local: true) do |form| %>
  <% if patient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(patient.errors.count, "error") %> prohibited this patient from being saved:</h2>

      <ul>
      <% patient.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="row">  
<div class="col-md-4"></div>

<div class="col-md-4">


  <%= form.file_field :photo, id: :patient_photo %>
  <label>
  <%= form.check_box :remove_photo %>
      Remove Photo
  </label>    

  <div class="field">
    <%= form.label :full_name %>
    <%= form.text_field :full_name, id: :patient_full_name %>
  </div>

  <div class="field">
    <%= form.label :date_of_birth %>
    <%= form.date_select :date_of_birth, id: :patient_date_of_birth, :start_year => 1900 %>
  </div>

  <div class="field">
    <%= form.label :gender %>
    <%= form.text_field :gender, id: :patient_gender %>
  </div>


 <div class="field">
    <%= form.label :id_type %>
    <%= form.text_field :id_type, id: :patient_id_type %>
  </div>

  <div class="field">
    <%= form.label :id_no %>
    <%= form.text_field :id_no, id: :patient_id_no %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address, id: :patient_address %>
  </div>

  <div class="field">
    <%= form.label :phone_no %>
    <%= form.text_field :phone_no, id: :patient_phone_no %>
  </div>

  <div class="field">
    <%= form.label :history %>
    <%= form.text_area :history, id: :patient_history %>
  </div>

  <div class="field">
    <%= form.label :treatment %>
    <%= form.text_area :treatment, id: :patient_treatment %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
  <%= link_to 'Show', @patient %> |
  <%= link_to 'Back', patients_path %>
<% end %>
</div>
<div class="col-md-4"></div>

app/views/patients/_form2.html.erb
<% if @patient.medicines %>

<%= @patient.medicines[1] %>

<% end %>

app/views/patients/edit.html.erb
<h1>Editing Patient</h1>

<%= render 'form', patient: @patient %>

app/views/patients/index.html.erb
  <p id="notice"><%= notice %></p>

<div class="container">

<h1>List of Patients</h1>

<% @patients.in_groups_of(3) do |group| %>
  <div class="row">
    <% group.compact.each do |patient| %>
      <div class="col-md-4">
        
       
        
      </div>
    <% end %>
  </div>
<% end %>






<table class="table table-responsive">
  <thead>
    <tr  >
      <th class="bg-warning">Full Name</th>
      <th class="table-active">Date of Birth</th>
      <th class="table-success">Gender</th>
      <th class="table-danger">Id Type</th>
      <th class="table-info">Id No</th>
      <th class="bg-success">Address</th>
      <th class="table-success">Phone No.</th>
      <th class="table-warning" colspan="3"></th>
    </tr>
  </thead>

  <tbody>
  
    <% @patients.each do |patient| %>
    <% if user_signed_in? %>
     <% if patient.user_id == current_user.id %>
       <tr >
        <td class="bg-warning"><%= link_to patient.full_name, patient %></td>
        <td class="table-active"><%= patient.date_of_birth %></td>
        <td class="table-success"><%= patient.gender %></td>
        <td class="table-danger"><%= patient.id_type %></td>
        <td class="table-info"><%= patient.id_no %></td>
        <td class="bg-success"><%= patient.address %></td>
        <td class="table-success"><%= patient.phone_no %></td>
        <td class="table-warning"><%= link_to 'Show', patient %></td>
        <td class="table-warning"><%= link_to 'Edit', edit_patient_path(patient) %></td>
        <td class="table-warning"><%= link_to 'Destroy', patient, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
    <% end %>
   <% end %> 
  </tbody>
</table>

<br>

<%= link_to 'New Patient', new_patient_path %>

</div>

app/views/patients/new.html.erb
<h1>New Patient</h1>

<%= render 'form', patient: @patient %>

app/views/patients/show.html.erb
    <p id="notice"><%= notice %></p>
 <div class="container">
  <p>
  <div class="row3">
    
  

  <h3>Patients Profile</h3>
    <strong></strong>
    <%= image_tag(@patient.photo_url, width: 100) if @patient.photo.present? %>
  
  </p>
  <p>
    <strong>Full name:</strong>
    <%= @patient.full_name %>
  </p>
  <p>
    <strong>Date of birth:</strong>
    <%= @patient.date_of_birth %>
  </p>
  <p>
    <strong>Gender:</strong>
    <%= @patient.gender %>
  </p>


  <p>
    <strong>Id type:</strong>
    <%= @patient.id_type %>
  </p>
 <p>
  <strong>Id no:</strong>
  <%= @patient.id_no %>
 </p>

 <p>
   <strong>Address:</strong>
   <%= @patient.address %>
 </p>

 <p>
   <strong>Phone no:</strong>
  <%= @patient.phone_no %>
</p>
 

<p>
  <strong>History:</strong>
  <%= @patient.history %>
</p>



<p>
  <strong>Treatment:</strong>
  <%= @patient.treatment %>
</p>
</div>


<h3>Medications</h3>
<div class="row">
<div class="col-md-6">
<% @medicines.each do |medicine| %>
    <strong><%= medicine.med_name %></strong> - <%= medicine.dosage %> - <%= medicine.in_take %> - <%= medicine.date %>
    <p><%= link_to 'Delete', medicine_path(medicine), method: :delete, data: { confirm: 'Are you sure?' } %></p>

<% end %>
</div>

<div class="col-md-6">
<%= render partial: 'medicines/form', locals: { medicine: @medicine } %>
</div>
</div>



<h3>Procedures</h3>

<div class="row">
<div class="col-md-6">

<% @procedures.each do |procedure| %>

    <strong><%= procedure.proc_name %></strong> - <%= procedure.proc_date %> - <%= procedure.performed_by %>
    <p><%= link_to 'Delete', procedure_path(procedure), method: :delete, data: { confirm: 'Are you sure?' } %></p>

<% end %>
</div>
<div class="col-md-6">
<%= render partial: 'procedures/form', locals: { procedure: @procedure } %>
</div>
</div>


<%= link_to 'Edit', edit_patient_path(@patient) %> |
<%= link_to 'Back', patients_path %>

</div>



</div>