config/routes.rb
Rails.application.routes.draw do

  resources :medicines
  resources :procedures
  resources :patients
  get 'pages/info'
 
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", registrations: "users/registrations" }
  
  root to: "pages#info"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/procedure.rb
class Procedure < ApplicationRecord
	belongs_to :patient
end

app/controllers/procedures_controller.rb
class ProceduresController < ApplicationController
  before_action :set_procedure, only: [:show, :edit, :update, :destroy]

  # GET /procedures
  # GET /procedures.json
  def index
    @procedures = Procedure.all
  end

  # GET /procedures/1
  # GET /procedures/1.json
  def show
    @procedure = Procedure.find(params[:id])
    @patient = @procedure.patient_id
  end
  

  # GET /procedures/new
  def new
    @procedure = Procedure.new
    @patient = @procedure.patient_id
  end

  # GET /procedures/1/edit
  def edit
  end

  # POST /procedures
  # POST /procedures.json
  def create
    @procedure = Procedure.new(procedure_params)
    respond_to do |format|
      if @procedure.save
        format.html { redirect_to @procedure, notice: 'Procedure was successfully created.' }
        format.json { render :show, status: :created, location: @procedure }
      else
        format.html { render :new }
        format.json { render json: @procedure.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /procedures/1
  # PATCH/PUT /procedures/1.json
  def update
    respond_to do |format|
      if @procedure.update(procedure_params)
        format.html { redirect_to @procedure, notice: 'Procedure was successfully updated.' }
        format.json { render :show, status: :ok, location: @procedure }
      else
        format.html { render :edit }
        format.json { render json: @procedure.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /procedures/1
  # DELETE /procedures/1.json
  def destroy
    if@procedure.destroy
    respond_to do |format|
      format.html { redirect_to procedures_url, notice: 'Procedure was successfully destroyed.' }
      format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_procedure
      @procedure = Procedure.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def procedure_params
      params.require(:procedure).permit(:proc_name, :proc_date, :performed_by, :patient_id)
    end
end

app/helpers/procedures_helper.rb
module ProceduresHelper
end

app/views/procedures/_form.html.erb
<%= form_with(model: procedure, local: true) do |form| %>
  <% if procedure.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(procedure.errors.count, "error") %> prohibited this procedure from being saved:</h2>

      <ul>
      <% procedure.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :procedure %>
    <%= form.text_field :proc_name, id: :procedure_proc_name %>
  </div>

  <div class="field">
    <%= form.label :procedure_date %>
    <%= form.date_select :proc_date, id: :procedure_proc_date %>
  </div>

  <div class="field">
    <%= form.label :performed_by %>
    <%= form.text_field :performed_by, id: :procedure_performed_by %>
  </div>


  <%= form.hidden_field :patient_id %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/procedures/edit.html.erb
<h1>Editing Procedure</h1>

<%= render 'form', procedure: @procedure %>

<%= link_to 'Show', @procedure %> |
<%= link_to 'Back', procedures_path %>

app/views/procedures/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Procedures</h1>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Proc name</th>
      <th>Proc date</th>
      <th>Performed by</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @procedures.each do |procedure| %>
      <tr>
        <td><%= procedure.id %></td>
        <td><%= procedure.proc_name %></td>
        <td><%= procedure.proc_date %></td>
        <td><%= procedure.performed_by %></td>
        <td><%= link_to 'Show', procedure %></td>
        <td><%= link_to 'Edit', edit_procedure_path(procedure) %></td>
        <td><%= link_to 'Destroy', procedure, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Procedure', new_procedure_path %>

app/views/procedures/new.html.erb
<h1>New Procedure</h1>

<%= render 'form', procedure: @procedure %>

<%= link_to 'Back', procedures_path %>

app/views/procedures/show.html.erb
<p id="notice"><%= notice %></p>


<p>
  <strong>Procedure:</strong>
  <%= @procedure.proc_name %>
</p>

<p>
  <strong>Procedure Date:</strong>
  <%= @procedure.proc_date %>
</p>

<p>
  <strong>Performed By:</strong>
  <%= @procedure.performed_by %>
</p>

<%= link_to 'Edit', edit_procedure_path(@procedure) %> |
<%= link_to 'Back', patient_path(@patient) %>